config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :customers
  resources :departments
  resources :quotes
  resources :vehicles
  resources :posts
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :customer
  belongs_to :employee
  belongs_to :vehicle
  belongs_to :user
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
    authorize @quotes
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    authorize @quotes
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
    authorize @quote
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)
    authorize @quotes
    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
      authorize @quotes
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:customer_id, :employee_id, :vehicle_id, :markup, :sales_tax, :total)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.text_field :employee_id %>
  </div>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.text_field :vehicle_id %>
  </div>

  <div class="field">
    <%= form.label :markup %>
    <%= form.text_field :markup %>
  </div>

  <div class="field">
    <%= form.label :sales_tax %>
    <%= form.text_field :sales_tax %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Employee</th>
      <th>Vehicle</th>
      <th>Markup</th>
      <th>Sales tax</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.customer %></td>
        <td><%= quote.employee %></td>
        <td><%= quote.vehicle %></td>
        <td><%= quote.markup %></td>
        <td><%= quote.sales_tax %></td>
        <td><%= quote.total %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @quote.employee %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @quote.vehicle %>
</p>

<p>
  <strong>Markup:</strong>
  <%= @quote.markup %>
</p>

<p>
  <strong>Sales tax:</strong>
  <%= @quote.sales_tax %>
</p>

<p>
  <strong>Total:</strong>
  <%= @quote.total %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>